language: php
php:
  - 7.0
script: 
  - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  # This one lists only files with erros
  # - find . -type f -name '*.php' -exec php -l {} \; |grep -v "No syntax errors detected"
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wpmktgengine/
  - secure: "nIhw0OAAdAGIqLdV7mJp6G/JRNHIlEmto5JfCj0RoTmcEzh/EuAsxCOwD9nRieUTz/uOgsTXke/xe8FO17Bfrck1BMWzCLXAoG2pWFwzvZgDKHoz7sZw7MSEoJ+drbzuizJNO+qI2a4CiZ8UiVylqsYmgijR4IpJsQeQbsXIGaA6/41Ot/PC9nnXltdqLRlZJLdND36qJ6B5S4lURdpI3ntRCJ3WTf+tm48wjd4zhgAOq4RjHrRKnKS0WXVhaIEV5x/8RKhfBm4r7KHGKugQYCL54colrS/Q0oanfuxQzKQcdHrGt0ykF9JQ3JdJWsROfZU5rRXAQYILnk+2juD1ulg1JkPlFTkLyZhJp+2H235be8Y2nTmLTg1leqWbi2XC84EnUUmYDbQda7jakbLP+42+tx0VsrbvmNcPjlA8iBh2acxSgp8q+BvWxGvhBYt/EvpT01LznAbLeY+MIOEZG0nHlBWMPJvXLvvxnabUW9PY6BMlKBbGxG47jC4dg09R3BlMgLjmmx6QqP2IERsI/wpUYUZw05RnY16SrTOnYckzIzIcve10jF0l3B3wQonWU2/ne/W6QgiOR+gy3aoeE02yxRuRRrfCCq9Q8BcbpGjybX5OOHqyMzr1iOZKU+fVl7rIr0m4qTA76iF0z9cstO07fQVgyNMXBz5A50yv8eE="
  - secure: "sgE1m1Abf4QD1Kvl1+RX7Dqtql96hMWfUSJPj7a/eKkdisE7IkRDjI4UGZaEUB9yDZ1XjPAwzJK/cKMgUNx+FmVxhfO8r7vN0fjCHJR0F2M7Lbo/Zx5KQZ243BvXeVjnPPsEvNj5Dao26a74YANxilL47wLi9hDS/vgq8L4FLKvueC8gjbtqXbm9PRZUtSbzTCejYZpqnUpma9oYlUGyrb5hdAi3rPhHqrmE9GmpJ8L4DKUmSivh2KQSugnK9THE59FNOQIn8NCaqIUvB68FY0rJTus8Q9aPFh1TF5UkI0qq/Z5ZwR7ZpxUNkobzqxutpYLdYBN17kb/gQNK/fAzwW3kf5lnWiSE8KDPEqU8V49xo/eXEGZP7fiVbSDY0YWB20DhFqIH8IrB7AYVBSndg++emOR9ozVLjQ9um1E6OSG31Z/jpc6sfx9Wk8Gl7snX2j6HzauuuQEc+oWIXwM2Q2ZzFHVg/G6nb26VhnvBzmdOzbyPdQrOfENN9umq/46bjsBIGKkVHS8n5/O9WDrtOuli8whRpiHB/WRlZAZs2TDMcOp3j1PDxUdykyCq0CDBAVxgGS/sJA/Nz1Ow2V1fbKsKNg0AecKtdna6AGzOfXD4fyeqygs3hd+aYZhryh4dVW+lfQxelNbB9bpRBIB+KxbLFp9SdtFpY5GL+2MpVsw="